### ISSUE TITLE
CopyFiles(pattern, targetOutput); not retaining folder structure

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1006] opened 2016-06-24 11:55 UTC
@patriksvensson I tested this now but it wont retain the folder structure all files copied to the root like this 
![image](https://cloud.githubusercontent.com/assets/362726/16337122/4e9c86fe-3a13-11e6-9f39-249518f79979.png) is this a bugg ?

```
var files = new [] {
        $"{buildDir}/bin/*.dll",
        $"{buildDir}/DataServices/*.svc",
        $"{buildDir}/scripts/**",
        $"{buildDir}/*.config",
        $"{buildDir}/*.aspx",
        $"{buildDir}/*.ico",
        $"{buildDir}/*.html"
    };
	
    foreach(var pattern in files) {
        CopyFiles(pattern, targetOutput);
    }
```

**Comment by patriksvensson** [comment] 2016-06-24 11:57
@robgha01 No, this is by design. We've discused adding an overload that keeps the structure in #899.
Closing this since there's already one for this issue.

**Closed by patriksvensson** 2016-06-24 11:57 UTC
