### ISSUE TITLE
Casing causes 'More than one build script specified.' message

### ISSUE THREAD

**Issue by kharlamov** [cake-build/cake#1690] opened 2017-07-19 14:48 UTC
I switched from windows _(ps1)_ to mac _(sh)_, and noticed that using commands such as -`T` or `-Target` on the shell script it causes the following issue `More than one build script specified`. After a while I noticed it was just a casing issue `-t` worked just fine. Is there anyway to get some better notification or just to ignore casing for this?

**Comment by patriksvensson** [comment] 2017-07-20 10:18
@kharlamov Command line options are case sensitive in bash, so this is by design.

**Comment by kharlamov** [comment] 2017-07-20 13:30
I guess that part makes sense, the weird part to me was the side effect when the command is wrong `More than one build script specified.`? However, thats no big deal now that I know, thank you.

**Comment by patriksvensson** [comment] 2017-07-20 18:16
@kharlamov That message is coming from Cake's parser so that we might want to look closer at.

Would you mind specifying what OS you're running on, which Cake version and what the command looks like to get this error?

**Comment by kharlamov** [comment] 2017-07-20 20:58
Sure, I am using mac OS X 10.12.5 with the latest version of cake.

**Comment by devlead** [comment] 2017-10-01 14:10
@kharlamov can you supply the command line used that causes the error?

**Comment by tuyen-vuduc** [comment] 2017-12-26 01:30
I faced the same issue when running scripts cloned from this repo https://github.com/xamarin/AndroidSupportComponents.

The running script is
```
exec mono ./tools/Cake/Cake.exe build.cake --target libs
```
Without `--target libs`, this issue will be gone; however, that's a custom argument of the script.

**Comment by devlead** [comment] 2017-12-26 05:59
When invoking Cake directly the syntax would be:
'exec mono ./tools/Cake/Cake.exe build.cake --target=libs`

**Comment by HofmeisterAn** [comment] 2018-11-23 15:15
Can confirm this issue, reproduce on Mac OS `10.14.1 (18B75)`.

**Comment by Preetham-P** [comment] 2019-11-20 20:28
> Able to reproduce this on `MacOS 10.14 (18A391)` with:
> 
> ```shell
> ./build.sh --target build
> ```
> 
> Also tried `-t`, `-target`, `-T`, `-Target`, `--Target`, but they don't work.
> 
> Edit:
> 
> Had to use `=` like:
> 
> ```
> ./build.sh --target=build
> ```

This Worked for me

**Comment by dem4gus** [comment] 2020-05-20 17:55
I think part of the problem is the documentation is not clear, especially when running a Bash script as opposed to PowerShell. The doc page about [running targets](https://cakebuild.net/docs/fundamentals/running-targets) gives these examples:

`./build.ps1 -Target Publish`

`./build.ps1 --target Publish --exclusive`

**Comment by augustoproiete** [comment] 2021-02-04 02:36
[The .NET Tool runner](https://cakebuild.net/docs/running-builds/runners/dotnet-tool) is nowthe recommended way to run Cake scripts on all platforms, the bootstrapping became a lot simpler ([a handful of lines of code](https://github.com/cake-build/resources/tree/master/dotnet-tool)) and the [documentation](https://cakebuild.net/docs/running-builds/runners/dotnet-tool#bootstrapping-for.net-tool) on the website has been updated.

Closing this as resolved as part of the 1.0.0 milestone. Feel free to reopen if needed.

**Closed by augustoproiete** 2021-02-04 02:36 UTC
Labels: Documentation
