### ISSUE TITLE
Add OutputDirectory property for Chocolatey Aliases

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1146] opened 2016-08-10 11:53 UTC
Once 0.10.0 is released:

https://github.com/chocolatey/choco/issues/598#event-751163113

**Comment by pascalberger** [comment] 2017-05-05 11:23
@gep13 This seems like a duplicate of #510 which was fixed with https://github.com/cake-build/cake/commit/b9183974d51c9fbb1b9e13cfa0e4b560fb73c502

**Comment by gep13** [comment] 2017-05-05 11:43
@pascalberger yes and no.

That commit is really tricking chocolatey into thinking that it is running in the specified output directory, hence, that is where the output file goes.

Now in the chocolatey client there is an option to specify the output directory.  The chocolatey aliases within Cake should correctly use that setting.

**Comment by gep13** [comment] 2017-05-05 11:44
i.e. within the ChocolateyPackRunner, set the `--outputdirectory` command line option.

**Comment by pascalberger** [comment] 2017-05-05 11:52
@gep13 Ah, missed this :) 

I can create a PR for this. Can we expect users to have Chocolatey >= 0.10.0 installed?

**Comment by gep13** [comment] 2017-05-05 11:55
@pascalberger that is a difficult one.

The stance I personally take on this is that the aliases should work against the current latest version of the underlying tool, however, we should probably do a check in this instance to make sure that the version is high enough before attempting to run that command.

Or, I wonder, would an earlier version of chocolatey just ignore it?  Perhaps worth a quick investigation.

**Comment by Roemer** [comment] 2017-06-01 07:50
Any news on this?

**Closed** 2022-11-07 10:54 UTC
Labels: Feature
