### ISSUE TITLE
Cannot give multiple nuget sources from the command line

### ISSUE THREAD

**Issue by aateeque** [cake-build/cake#2070] opened 2018-03-06 15:38 UTC
### What You Are Seeing?

Parameter `nuget_source` when set with multiple sources only sets a single nuget repository.

### What is Expected?

Create a nuget repository for each of the source specified at the command line

### What version of Cake are you using?

0.26.1

### How Did You Get This To Happen? (Steps to Reproduce)

Start cake.exe as

```
cake.exe build.cake --nuget_source=http://corp.nuget/feed;http://corp.nuget.mirror/feed;https://myownfeed.internal/api
```

Cake only looks for packages in `http://corp.nuget/feed;http://corp.nuget.mirror/feed;https://myownfeed.internal/api` which is an invalid nuget repository and no packages are found

**Comment by mholo65** [comment] 2018-03-06 15:41
Duplicate of https://github.com/cake-build/cake/issues/2014

**Closed by mholo65** 2018-03-06 15:41 UTC
