### ISSUE TITLE
Publish as .NET Core Global Tool

### ISSUE THREAD

**Issue by bruno-garcia** [cake-build/cake#2067] opened 2018-03-04 16:50 UTC
Last week the .NET Core team [released a preview for version 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/).
With this release the CLI now support what they called: *.NET Core Global Tools*.

To quote the announcement:

> .NET Core tools are .NET Core console apps that are packaged and acquired as NuGet packages. By default, these tools are framework-dependent applications and include all of their NuGet dependencies. This means that a given global tool will run on any operating system or chip architecture by default. You might need an existing tool on a new version of Linux. As long as .NET Core works there, you should be able to run the tool.

It'd look like
```shell
dotnet install tool -g cake
```

I believe #1644 is related but now Global Tools is the way to go.

**Comment by ErikSchierboom** [comment] 2018-06-19 07:53
I was wondering if anyone is working on this? I know Cake now has a .NET Core compatible build, so hopefully it shouldn't be too much work.

**Comment by patriksvensson** [comment] 2018-06-19 07:58
@ErikSchierboom We're having a meeting in a couple of weeks where we will discuss road map and similar. I will make sure to put this on the agenda.

**Comment by pitermarx** [comment] 2018-06-19 08:43
My 2c.
Actually being installed via bootstrapper is a big win on my eyes. It allows me to upgrade the build tools easily while still using the same build server adding to the reproducibility of the build. I'm willing to pay the penalty of making sure that cake is installed on every build if it improves my confidence that the build is reproducible. 
But then again I **ALWAYS** pin my dependencies. I know for a fact that this is (unfortunately) not a thing that everybody does.

**Comment by ErikSchierboom** [comment] 2018-06-19 10:59
@patriksvensson Okay, cool! 

@pitermarx I understand your point, but you can also install tools in a directory of your choice and with a specific version:

<pre>
C:\Code> dotnet tool install --help
Usage: dotnet tool install [options] <PACKAGE_ID>

Arguments:
  <PACKAGE_ID>   NuGet Package Id of the tool to install.

Options:
  -g, --global            Install user wide.
  --tool-path             Location where the tool will be installed.
  --version               Version of the tool package in NuGet.
  --configfile            The NuGet configuration file to use.
  --add-source <SOURCE>   Adds an additional NuGet package source to use during installation.
  --framework             The target framework to install the tool for.
  -h, --help              Show help information.
  -v, --verbosity         Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
</pre>

**Comment by pitermarx** [comment] 2018-06-19 16:49
and can i install 2 versions and choose the one i want to run?

**Comment by ErikSchierboom** [comment] 2018-06-19 17:03
Eh yes, sure you can:

```
dotnet tool install --version 2.0.0 --tool-path ./tools/cake-2.0.0
dotnet tool install --version 2.1.0 --tool-path ./tools/cake-2.1.0
```

And then you can just use the tool shortcut that is located in the respective tools directory.

**Comment by pitermarx** [comment] 2018-06-19 17:23
OK, that's dumb of me... If I install it locally it's not a global tool...
Then I'm in.
I'll just say that it would be a good recommendation to say that cake should not be installed globally

**Comment by gep13** [comment] 2018-06-19 17:32
Why? Depending on your use case, this is perfectly valid. It is already possible to install Cake globally today using either Chocolatey on Windows, or Homebrew on Mac.

**Comment by pitermarx** [comment] 2018-06-19 17:35
Sure it depends on the use case but for a build server that may build things that depend on different cake versions a global tool would not be a good fit.
Unless you're building in a container. In that case, lucky you

**Comment by aateeque** [comment] 2018-06-21 16:07
Wouldn't you be making an explicit choice in that case (the case being not pinning cake version) for whatever version of Cake you get globally or via your bootsrapper?
Would be important for Cake global tool to not break version pinning though

**Comment by n-sidorov** [comment] 2018-08-09 14:13
Any news on that?

I've actually tried repackage Cake project as dotnet tool locally and it seems to be working pretty well (the only changes are in Cake.csproj file). 

Having ability to `dotnet cake build.cake -Target=build" is great!

Which is also quite nice about using dotnet tools is that after you install it, you don't need mono to run Cake then (well, to some extent).

**Comment by devlead** [comment] 2018-08-13 09:07
@n-sidorov yes, I started working on this before summer vacation, just back from vacation and the plan is to have a PR ready by this or next week.

**Closed** 2018-08-15 15:54 UTC
Labels: Feature
