### ISSUE TITLE
Don't show delegating tasks in summary

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#639] opened 2016-01-14 21:42 UTC
i.e. Tasks that are only used to tie together other tasks.  If there is no action associated with the Task, don't show it in the summary.

**Comment by patriksvensson** [comment] 2016-01-14 21:48
:+1:

**Comment by RichiCoder1** [comment] 2016-01-15 19:59
Or show it in a non-tasky way to may it clear it's a summary or branch task.

**Comment by ErikSchierboom** [comment] 2016-01-22 11:22
How would you like the delegating task to be displayed? In grey, just like skipped tasks? And what should be the displayed text?

**Comment by ErikSchierboom** [comment] 2016-01-24 13:06
In a previous PR, I add a `Skipped` property to the `CakeReportEntry` class. However, I now think that should really have been an enumeration. That way, we can have an enumeration that specifies the executed task's status: `Executed`, `Skipped` or `Delegated`. Should I replace the boolean property with an enumeration, or create an additional boolean property?

**Comment by patriksvensson** [comment] 2016-01-24 14:36
@ErikSchierboom I agree with your thinking. An enum would be much cleaner. Not sure yet how the delegating task should be displayed. Not against graying it out, but the total won't match the sum of the tasks (since tasks that "delegate" could take some milliseconds). Not sure if this really matters. Maybe we can write the time for the delegated task but gray it out? 

What do you think?

(ping @gep13 @devlead)

**Comment by devlead** [comment] 2016-01-24 14:39
Gray is nice, but as build server logs are just text might not clear enough. Maybe just report on diagnostic / verbose?

**Comment by patriksvensson** [comment] 2016-01-24 14:40
@devlead Reports are not written to the log.

**Comment by devlead** [comment] 2016-01-24 14:43
Usually build servers display console output as log right?

**Comment by patriksvensson** [comment] 2016-01-24 14:45
@devlead Yes, they are. But we're writing the report using `IConsole` (and not `ICakeLog`) beacuse we want to do "pretty printing" of the summary (using colors).

**Comment by devlead** [comment] 2016-01-24 14:49
I understand that, colors rarely preserved on CI, so just an esthetic when running local then?

**Comment by patriksvensson** [comment] 2016-01-24 14:52
@devlead Yes, exactly. So the question is if we:

1. Exclude "delegating" tasks (so they won't show up in either log) 
2. Grey them out
3. Grey them out and add some description that tells the user that they just branched of to other tasks.

**Comment by devlead** [comment] 2016-01-24 14:56
Ok, I would vote hide by verbosity so they're shown if diagnostic.

**Comment by patriksvensson** [comment] 2016-01-24 15:01
@devlead That is a good idea. 

@ErikSchierboom What do you think about that?

**Comment by ErikSchierboom** [comment] 2016-01-24 15:11
Hiding by verbosity seems like a good idea! Should I only show the duration in gray, or also the task itself?

**Comment by devlead** [comment] 2016-01-24 15:16
I think both. @patriksvensson ?

**Comment by patriksvensson** [comment] 2016-01-24 15:16
@ErikSchierboom @devlead Maybe we need to think about this some more. I think we might get issues posted for this otherwise like `BUG: Some task is not shown unless using diagnostic verbosity`.

**Comment by patriksvensson** [comment] 2016-01-24 15:17
@ErikSchierboom @devlead Maybe we need to add a description like we did with `Skipped`.

**Comment by patriksvensson** [comment] 2016-01-24 16:00
OK, maybe we should just go with the one we agreed on and figure this out later? It's probably good :smile:

**Comment by ErikSchierboom** [comment] 2016-01-24 16:20
But what *is* the one we agreed on? The one with the verbosity? Or with the description?

**Comment by patriksvensson** [comment] 2016-01-24 19:15
Sorry, I meant the one with verbosity.

**Comment by ErikSchierboom** [comment] 2016-01-26 08:23
I've create a [PR](#660) to implement this functionality. I believe that issue #123 is a duplicate of this one by the way.

**Closed** 2016-01-31 20:25 UTC
