### ISSUE TITLE
Setup/Teardown should provide ICakeContext

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#743] opened 2016-03-08 15:53 UTC
The `Setup`/`Teardown` methods on the `ScriptHost` does not provide a `ICakeContext` for the delegate. Of course we will still have to support the old way, but would like those method to be a `Action<ICakeContext>` instead of a parameterless `Action`.

**Comment by gep13** [comment] 2016-03-09 12:25
@patriksvensson this would allow the overall assertion of whether a build succeeded or not in the Teardown method, right?

**Comment by devlead** [comment] 2016-03-09 12:42
@gep13 would be nice if one in the tear down could get a hold of last exception / errror

**Comment by patriksvensson** [comment] 2016-03-09 12:44
@gep13 @devlead Yes, Maybe we should provide a `ISetupContext` and a `ITeardownContext` just as we do with task setup/teardown.

**Comment by gep13** [comment] 2016-03-09 12:44
@devlead @patriksvensson :+1:

**Comment by devlead** [comment] 2016-03-09 12:46
@patriksvensson @gep13  :+1:

**Comment by gep13** [comment] 2016-03-10 07:36
@patriksvensson is this issue a duplicate of this one: https://github.com/cake-build/cake/issues/686

**Comment by patriksvensson** [comment] 2016-03-10 08:27
@gep13 Yes. Kind of :smile:

**Comment by gep13** [comment] 2016-03-10 08:56
Should we close the other one, and leave only this one?

**Comment by patriksvensson** [comment] 2016-03-10 09:26
@gep13 Yes. I'll do that.

**Closed** 2016-04-15 07:25 UTC
Labels: Improvement, in progress
