### ISSUE TITLE
Installation of xunit.runner.console 2.4.0 is slow 

### ISSUE THREAD

**Issue by mvestergaard** [cake-build/cake#2219] opened 2018-07-24 22:33 UTC
This one is a bit weird, and not necessarily anything Cake is causing.

Recently, xunit.runner.console 2.4.0 was released, and for some reason it is much slower to install than 2.3.1

```
Installing xunit.runner.console 2.4.0.
Completed installation of xunit.runner.console 2.4.0
Executing nuget actions took 1,04 min
```

```
Installing xunit.runner.console 2.3.1.
Completed installation of xunit.runner.console 2.3.1
Executing nuget actions took 525,02 ms
```

Any idea what may be causing this?

**Comment by mvestergaard** [comment] 2018-07-24 22:41
There are a few other issues here about a bug in nuget caused by signed packages. And I can see that 2.4.0 is signed, which 2.3.1 wasn't. Might that be the cause?

**Comment by pascalberger** [comment] 2018-07-25 06:05
@mvestergaard Which version of Cake are you using? Is Cake using the in-proc or external NuGet client? If you're using the external NuGet client which version of NuGet are you using?

Can you reproduce the behavior if you're installing the `xunit.runner.console` package on your environment using `nuget.exe`?

**Comment by mvestergaard** [comment] 2018-07-25 08:16
@pascalberger Sorry, I forgot to mention that. I'm currently on 0.29.0 but i tried downgrading to 0.27.0 which had the same behavior.
I also tried forcing a different version of nuget, I'm not sure i did it the correct way though. I changed the URL in build.ps1. I believe i tried downgrading to nuget 4.5.1, same result.

**Comment by mvestergaard** [comment] 2018-07-25 08:22
@pascalberger Okay, I think I misunderstood what you mean by in-proc nuget. I tried running with `--nuget_useinprocessclient=false`  and that "fixes" the issue.

**Comment by mvestergaard** [comment] 2018-07-25 11:33
I've tried making a simple little replication project that just installs xunit via cake and nothing else, but it seems like it somehow relates to how much else is in the project, because it works fine in this little test.

However in our main repository we have about 350 projects, and it kind of seems like it tries to restore all of those when it installs xunit via cake.

**Comment by mvestergaard** [comment] 2018-08-13 11:40
This may be caused by the same thing as #2207

**Comment by patriksvensson** [comment] 2018-08-15 16:42
Closing this since #2207 have been closed.
Feel free to reopen if problem remains in 0.30.0.

**Closed by patriksvensson** 2018-08-15 16:42 UTC
