### ISSUE TITLE
Loading Cake script from NuGet and from local filesystem does not work

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#1527] opened 2017-03-09 11:57 UTC
Affected version Cake 0.18.0 on Windows 64 bit

When having the following two cake scripts:
https://gist.github.com/Sam13/fbcef707aec67f8c7274230fc1f9c6ec

and try to run
`cake.exe Build.cake -target=Hello2`
the following error is reported:
`Error: The target 'Hello2' was not found.`

When loading the `Build2.cake` before the NuGet package the target is executing. 
Note: target `Hello1` cannot be executed in both cases. It seems that after loading scripts from NuGet no further processing occurs.

Sorry, can't provide a public NuGet package. When trying to use `Cake.Recipe` it crashes already in `Setup()`.

**Comment by gep13** [comment] 2017-03-09 12:01
@patriksvensson do you have any thoughts on this one?  Certainly don't think that this was intended.

**Comment by patriksvensson** [comment] 2017-03-10 06:09
@Sam13 @gep13 I can not reproduce this. The only thing that differs with your script is that I added a reference to the `Cake.Recipe` package instead of your build script package.

```csharp
#load "nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Recipe&prerelease"
#load Build2.cake
```

And the output is this:

```
Patrik@SHEPPARD [C:\Users\Patrik\Desktop\test] [master] > .\build.ps1 -Script .\build.cake -Target Hello2
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...
Setting up tools...

----------------------------------------
Setup
----------------------------------------
Executing custom setup action...
  ____         _              _   _         _  _
 / ___|  __ _ | | __  ___    | | | | _ __  (_)| |_  _   _
| |     / _` || |/ / / _ \   | | | || '_ \ | || __|| | | |
| |___ | (_| ||   < |  __/ _ | |_| || | | || || |_ | |_| |
 \____| \__,_||_|\_\ \___|(_) \___/ |_| |_||_| \__| \__, |
                                                    |___/

Starting Setup...
Calculating Semantic Version...
Calculated Semantic Version: 0.1.0
Building version 0.1.0 of Cake.Unity (Release, Hello2) using version 0.18.0.0 of Cake. (IsTagged: False)

========================================
Hello2
========================================
Executing task: Hello2
Hello2
Finished executing task: Hello2

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Finished running tasks.

Task                          Duration
--------------------------------------------------
Hello2                        00:00:00.0072316
--------------------------------------------------
Total:                        00:00:00.0072316
```

**Comment by gep13** [comment] 2017-03-10 08:20
>@Sam13 said...
Sorry, can't provide a public NuGet package.

That's ok.  Can you show us though the structure of the NuGet package?  Just want to make sure that something else isn't causing a problem there.

>@Sam13 said..
When trying to use Cake.Recipe it crashes already in Setup().

Can you show the output that you are getting?  I have ran Cake.Recipe on almost 30 projects, with no issues so far.

**Comment by Sam13** [comment] 2017-03-10 10:52
@gep13 @patriksvensson 
My package contains about 20 .cake files in the root directory of the package and one .cake file which loads all those files (similar to `load.cake` in `Cake.Recipe`). I already tried to move all scripts into the content subfolder (as in `Cake.Recipe`) but does not change anything.
When I download my NuGet package before running Cake and load the scripts in Cake from local file system it works, so I don't expect something is wrong with the package itself...


When I reference `Cake.Recipe` (as @patriksvensson) did and call
`cake.exe -target=Hello2 -verbosity=diagnostic`
I get the following output / error:

```
...
Compiling build script...

----------------------------------------
Setup
----------------------------------------
Executing custom setup action...

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Finished running tasks.
Error: System.NullReferenceException: Object reference not set to an instance of
 an object.
   at Cake.Figlet.Figlet.ToAsciiArt(String text)
   at Submission#0.Figlet(String text)
   at Submission#0.<.ctor>b__15(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.PerformSetup(Action`1 action, ICakeCont
ext context)
   at Cake.Core.CakeEngine.PerformSetup(IExecutionStrategy strategy, ICakeContex
t context)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy st
rategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, D
iagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script scr
ipt)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath
, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

Note: I'm calling `cake.exe` directly and do not use the powershell bootstrapper.

**Comment by skogsaas** [comment] 2017-04-24 07:24
@patriksvensson @Sam13 

I just experienced the same problems with a similar setup (v0.19.4). It seems loading a nuget package with .cake scripts located in the ROOT folder of the nuget-package structure makes cake behave strange. Among other things; it tried to call the same tasks multiple times, tried to locate the nuspec-file of the loaded nuget-package in the same folder as my build.cake, and was unable to find tasks defined.

I noticed a difference between the nuget folder structure @Sam13 had, and the packaged Cake.Recipe. By moving all my .cake files into the "content" folder, it seems Cake accepts them much better.

```
./util1.cake
./util2.cake
```
VS:
```
./content/util1.cake
./content/util2.cake
```

This worked for me, so I hopes it helps to reproduce this 👍

**Comment by devlead** [comment] 2017-09-24 10:24
Discussed internally with the  @cake-build/cake-team and we've have come to the conclusion that placing content in the root isn't best practice (we've done this mistake before with addins). So we're going to close this issue with the recommendation that scripts should be placed in the content folder.

**Closed by devlead** 2017-09-24 10:24 UTC
Labels: Bug

**Comment by Sam13** [comment] 2017-09-25 11:19
@devlead Even if I put my scripts into the _content_ subfolder the original problem still remains.
I will try to debug that on my environment...

**Comment by devlead** [comment] 2017-09-25 11:49
try clearing your tools folder and upgrade to latest version of Cake just so you're not chasing an old solved issue.

**Comment by Sam13** [comment] 2017-10-12 15:20
@devlead Today I was able to debug the issue.
The problem is that all *.cake files from the NuGet package are loaded even if an include statement is specified. The `NuGetLoadDirectiveProvider` adds another include statement (method `Load`, line 46).

E.g.
`#load nuget:?package=BuildScripts.Cake&version=1.0.0.115109&include=Content/Defaults.cake`
will become
`#load nuget:?package=BuildScripts.Cake&version=1.0.0.115109&include=Content/Defaults.cake&include=./**/*.cake`

My NuGet package contains other scripts which I don't want to load. This scripts contain `RunTarget(...)` itself and will cause an incorrect graph creation. The graph is only created for targets before the first `RunTarget(...)`. This is the reason why the target was not found (see my initial post).

My proposal would be to only add an include in `NuGetLoadDirectiveProvider` if none specified.
What do you think?

**Comment by devlead** [comment] 2017-10-12 16:22
Agree to not add an include when one is specified sounds reasonable to me. Please raise a separate issue for that. 

For now you could probably add an exclude to remove individual files /patterns.
