### ISSUE TITLE
Changing version of nuget package used in #load does not download latest nuget package

### ISSUE THREAD

**Issue by mabead** [cake-build/cake#1572] opened 2017-04-17 17:15 UTC
### What You Are Seeing?

I have a build.cake script that contains the following pre-processor directive:

    #load "nuget:?package=MyPackage&version=0.1.0-feat-mg-16017-co0020"

I can successfully build my project through `build.ps1`. But then, I want to use a new version of this nuget package. I therefore change my load directive to use version 21:

    #load "nuget:?package=MyPackage&version=0.1.0-feat-mg-16017-co0021"

When I start build.ps1, it continues to use version 20.

### What is Expected?

build.ps1 / cake should download version 21 of my nuget pacakge and use it.

### What version of Cake are you using?

0.19.3

### Are you running on a 32 or 64 bit system?

64

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

See above

**Comment by devlead** [comment] 2017-04-17 17:22
This is an known issue/limitation, It's ok the radar to be fixed, but not the current highest priority.

The workaround we recommend for now is to do a checksum on build.cake/packages.config and clear tools/addins if that changes.

You can see an example of this in the recommended build.ps1/build.sh in
https://github.com/cake-build/resources

**Comment by gep13** [comment] 2017-08-04 12:45
Closing as a duplicate of https://github.com/cake-build/cake/issues/1521

**Closed by gep13** 2017-08-04 12:45 UTC
Labels: Improvement
