### ISSUE TITLE
GitVersionRunner: error when deserializing Cake.Common.Tools.GitVersion.GitVersion

### ISSUE THREAD

**Issue by DixonDs** [cake-build/cake#1803] opened 2017-09-15 13:27 UTC
Here is the full stacktrace:
```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Cake.Common.Tools.GitVersion.GitVersion. The value '' cannot be parsed as the type 'Int32'. ---> System.Xml.XmlException: The value '' cannot be parsed as the type 'Int32'. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(String value, NumberStyles style)
   at System.Xml.XmlDictionaryReader.ReadElementContentAsInt()
   at ReadGitVersionFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at Cake.Common.Tools.GitVersion.GitVersionRunner.Run(GitVersionSettings settings)
   at Submission#0.BuildParameters.GetParameters(ICakeContext context)
```

You can reproduce it if you run `build.ps1` from https://github.com/DixonDs/Cake.Azure/tree/10398e18289e9d705ac655fbee3387dfd56e70af

**Comment by gep13** [comment] 2017-09-15 14:26
This is a duplicate of https://github.com/cake-build/cake/issues/1798 which is due to be fixed in 0.22.1.

**Closed by gep13** 2017-09-15 14:26 UTC
