### ISSUE TITLE
Inc on array throws AccessViolationException

### ISSUE THREAD

**Issue by MihaMarkic** [cake-build/cake#829] opened 2016-04-18 10:46 UTC
This code kills Cake.

`int[] v = new int[] { 0};
v[0]++;
`
Running on Windows 10 x64.

Exception:

> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Submission#0.<.ctor>b__0()
>    at Cake.Core.ActionTask.Execute(ICakeContext context)
>    at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
>    at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
>    at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
>    at Cake.Scripting.BuildScriptHost.RunTarget(String target)
>    at Submission#0..ctor(Session session, Object& submissionResult)
>    at Submission#0.<Factory>(Session session)
>    at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
>    at Roslyn.Scripting.Session.Execute(String code)
>    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
>    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
>    at Cake.CakeApplication.Run(IEnumerable`1 args)
>    at Cake.Program.Main()

**Comment by devlead** [comment] 2016-04-18 10:53
Confirmed issue, but works as expected with experimental & mono.

**Comment by patriksvensson** [comment] 2017-07-30 21:41
Closed since #1645 been merged to develop. Feel free to reopen this if it's still a problem after 0.22.0 have been released.

**Closed by patriksvensson** 2017-07-30 21:41 UTC
Labels: Bug
