### ISSUE TITLE
SSL issue with the cake installer

### ISSUE THREAD

**Issue by mathieukempe** [cake-build/cake#1903] opened 2017-10-30 06:41 UTC
### What You Are Seeing?

Tried on a few computers, ask other people to try with same result

```ps
Invoke-WebRequest https://cakebuild.net/download/bootstrapper/windows -OutFile build.ps1
```
```ps
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest https://cakebuild.net/download/bootstrapper/windows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

### What is Expected?

Should install cake

### What version of Cake are you using?
Latest

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
windows

### Are you running on a CI Server?  If so, which one?
No
### How Did You Get This To Happen? (Steps to Reproduce)

was working last week, does not work today

**Comment by devlead** [comment] 2017-10-30 07:41
There was a recent Windows update that changes handling of SSL redirects, We'll see if we can sort something server side othwerwise we'll adapt the bootstrappers.

**Comment by devlead** [comment] 2017-10-30 08:16
Now got word from out SSL provider cloud flare that it certs renewed this weekend might have issues and that they're working on, got a support ticket and get back here as soon as we get an update.

**Comment by heberop** [comment] 2017-10-30 17:09
Following [this reference](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel), I put this line in build.ps1 and the script works fine.

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by gep13** [comment] 2017-10-30 17:44
I am going to go ahead and close this as a duplicate of this: https://github.com/cake-build/cake/issues/1904

**Closed** 2017-10-30 17:44 UTC
