### ISSUE TITLE
msbuild properties incorrectly escaped

### ISSUE THREAD

**Issue by wkwood** [cake-build/cake#2274] opened 2018-09-07 13:58 UTC
In Cake 0.30 on Win 10, 64 bit using VS 2017 I'm encountering an issue with multiple reference paths being handled in msbuild.

Cake is escaping a quoted string with semi-colons which should be necessary and is causing the passed /p:ReferencePath property to be literally %3B instead of the semi-colons.

In my cake script I quote a series of dependency folders, separated by semi colons, here is the literal property string being passed in the attached example:

**"deps/json;deps/log4net;"**

This gets escaped to be "deps/json%3Bdeps/log4net%3B" which isn't interpreted correctly by msbuild and is concatenated as one long path, not two separate paths.  This is the diagnostic output that's passed to msbuild:

**Executing: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/amd64/MSBuild.exe" /v:normal /p:Configuration="Release" /p:ReferencePath="deps/json%3Bdeps/log4net%3B" /target:Build "D:/cake-example/src/Example.sln"**

To fix the problem locally, I've attached a fix for MSBuildPropertyExtensions which doesn't escape a quoted string.  I've attached an example of the problem based on cake-example along with the log and the patch.diff file.
[log.txt](https://github.com/cake-build/cake/files/2361277/log.txt)

[cake-example-referencepathissue.zip](https://github.com/cake-build/cake/files/2361274/cake-example-referencepathissue.zip)
[patch-diff.txt](https://github.com/cake-build/cake/files/2361280/patch-diff.txt)

**Comment by jnm2** [comment] 2018-09-08 16:47
Duplicate of https://github.com/cake-build/cake/issues/1852.

**Comment by augustoproiete** [comment] 2021-02-06 04:27
Thanks @jnm2.

Closing as duplicate of #1852.

**Closed by augustoproiete** 2021-02-06 04:27 UTC
Labels: Duplicate
