### ISSUE TITLE
Cake 0.29.0 corrupt on nuget

### ISSUE THREAD

**Issue by philpowers** [cake-build/cake#2223] opened 2018-07-28 19:02 UTC
### What You Are Seeing?
Cake 0.29.0 hosted on nuget seems to be corrupt. I've verified this on several machines: https://www.nuget.org/api/v2/package/Cake/0.29.0

It cannot be installed through nuget/paket, and it even cannot be opened as a ZIP file.

### What environment are you running on?  Windows? Linux? Mac?
Windows

**Comment by patriksvensson** [comment] 2018-07-28 19:06
@philpowers I use Cake 0.29.0 in a lot of projects (commercial and private) and I have no problem with it. I can also open it as a zip file without problem.

![image](https://user-images.githubusercontent.com/357872/43359833-1991476e-92aa-11e8-984c-7acd8ef7e572.png)

**Comment by philpowers** [comment] 2018-07-28 19:12
Hmm maybe it's a load-balancing / distribution problem?  The nuget URL redirects me to this file, which is corrupt and only 4.5 megs: https://az320820.vo.msecnd.net/packages/cake.0.29.0.nupkg

**Comment by philpowers** [comment] 2018-07-28 19:19
![image](https://user-images.githubusercontent.com/2119127/43359901-90d30a1e-9279-11e8-8f2c-b8c8358436e8.png)

**Comment by patriksvensson** [comment] 2018-07-28 19:47
@philpowers According to whois that domain seems to be registered to Microsoft so there's probably nothing malicious going on. Not sure how to help you here to be honest. Perhaps reach out to NuGet directly and see if they know anything?

**Comment by philpowers** [comment] 2018-07-28 19:56
@patriksvensson This seems to be the exact issue I am seeing: https://github.com/NuGet/Home/issues/5076

Someone mentions msecnd.net being part of Azure Block Storage. The resolution was for the NuGet people to reset their CDN cache.

Anyway, for now I've retargeted back to Cake 0.28.1, which doesn't have the same problem for me. I'm assuming that I'm not the only one who's seeing this, though. For what it's worth, I'm in FL - I'm guessing it's a geographical thing.

Thanks for looking into it.

**Comment by patriksvensson** [comment] 2018-08-15 16:36
Closing this issue for now since we can't reproduce it. Feel free to reopen if you have any more information.

**Closed by patriksvensson** 2018-08-15 16:36 UTC
