### ISSUE TITLE
Referencing addins that contain multiple assemblies throws an error

### ISSUE THREAD

**Issue by SharpeRAD** [cake-build/cake#410] opened 2015-09-12 11:29 UTC
Example:

```C#
#addin "RestSharp"
```

Throws "An assembly with the same simple name 'RestSharp' has already been imported"

**Comment by devlead** [comment] 2015-09-12 15:46
Hi believe this is a duplicate of  #373 , issue occurs when nuget is multi target, we need to fix identifying best match dll.

**Closed by devlead** 2015-09-12 15:46 UTC
Labels: duplicate
