### ISSUE TITLE
Cake unable to build projects because the nuget package "Roslyn.Compilers.CSharp" has been unlisted

### ISSUE THREAD

**Issue by NachbarsLumpi** [cake-build/cake#1583] opened 2017-04-26 08:20 UTC
### What You Are Seeing?
A red line indicating that it does not work anymore. ;-) See output log section for more information.

### What is Expected?
A build should be started. ;-) See output log section for more information.

### What version of Cake are you using?
Tested with 0.19.1, 0.19.3 and 0.19.4. 0.19.4 includes further a regression and does not display an sensible error message, but rather only "Error: An error has occurred.".

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Happens both on the CI server, but on developer machines as well.

### How Did You Get This To Happen? (Steps to Reproduce)
Upgraded cake from 0.19.1 to 0.19.4.

### Output Log

Cake==0.19.1 || Cake==0.19.3:

~~~sh
powershell.exe -executionpolicy RemoteSigned -command "build.ps1" -Script build.cake -Configuration Debug
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Downloading and installing Roslyn...
Installing packages (using https://packages.nuget.org/api/v2)...
Error: Unable to find version '1.2.20906.2' of package 'Roslyn.Compilers.CSharp'.
~~~

Cake==0.19.4:
~~~sh
powershell.exe -executionpolicy RemoteSigned -command "build.ps1" -Script build.cake -Configuration Debug
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Downloading and installing Roslyn...
Installing packages (using https://packages.nuget.org/api/v2)...
Error: An error has occurred.
~~~

**Comment by mholo65** [comment] 2017-04-26 08:23
Duplicate of #1582

**Comment by mholo65** [comment] 2017-04-26 08:25
Unlisted packages should be available for download.

This is more likely due to that NuGet are currently experiencing issues. See their https://status.nuget.org/ for more info.

**Closed by mholo65** 2017-04-26 08:25 UTC
