### ISSUE TITLE
TeamCity: add ImportCoverageData method

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#499] opened 2015-11-06 17:22 UTC
Currently `ITeamCityProvider` has `void ImportData(string type, FilePath path)`, but when importing coverage data, an additional `tool` attribute is required ([TeamCity docs](https://confluence.jetbrains.com/display/TCD9/Manually+Configuring+Reporting+Coverage)):

> `##teamcity[importData type='dotNetCoverage' tool='<tool name>' path='<path to the results file>']`
> where tool name can be dotcover, partcover, ncover or ncover3.

**Comment by gep13** [comment] 2015-11-06 20:49
This would be another great addition! :+1:

**Comment by patriksvensson** [comment] 2015-11-06 21:38
I agree :+1:

**Comment by mholo65** [comment] 2016-03-14 20:01
Duplicate of #723 and PR pending in #714 

(Sorry for not noticing this when I created issue #723)

**Comment by devlead** [comment] 2016-05-13 14:27
Fixed by #714

**Closed by devlead** 2016-05-13 14:27 UTC
Labels: Improvement
