### ISSUE TITLE
Cake leaves bunch of dotnet.exe processes behind after finishing

### ISSUE THREAD

**Issue by ryudice** [cake-build/cake#2285] opened 2018-09-13 20:49 UTC
### What You Are Seeing?
After executing cake a bunch of dotnet.exe processes are created and never killed by cake eventhoguht it's no longer running.
### What is Expected?
dotnet.exe processes should be killed. I also get file lock issues due to this.

### What version of Cake are you using?
Cake.Incubator version=3.0.0

### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
windows
### Are you running on a CI Server?  If so, which one?
no

### How Did You Get This To Happen? (Steps to Reproduce)
Just run Cake, here is my build.cake that causes the issue:

`
```
#addin "Cake.Docker"
#tool "nuget:?package=GitVersion.CommandLine"
#addin "Cake.Powershell"
#tool "nuget:?package=JetBrains.dotCover.CommandLineTools"
#addin nuget:?package=Cake.Sonar
#addin "nuget:?package=Cake.Incubator&version=3.0.0"
#tool nuget:?package=MSBuild.SonarQube.Runner.Tool&version=4.3.1

var target = Argument("target", "Publish Docker");
var solution = "JobAlerts.sln";
var schedulerRepository = "";
var schedulerProjectDir = Directory("src/JobAlerts.Scheduler");
var version = GitVersion().LegacySemVer;
var dockerTag = $"{schedulerRepository}:{version}";
var SONARQUBE_URL = EnvironmentVariable<string>("SONAR_URL", "http://sonarqube.aws");

var defaultKey = System.IO.Path.GetFileName(solution).Replace(".sln", "").Replace('.','-').ToLower();
var sonarProjectKey = EnvironmentVariable<string>("SONAR_PROJECT_KEY", defaultKey);

Task("Build solution")
.Does( ()=> {
    Information("Building solution");

    DotNetCoreBuild(solution);

});

Task("Build scheduler docker")
.IsDependentOn("Build solution")
.Does(()=>
{
    var buildSettings = new DockerImageBuildSettings(){
        Tag = new [] { dockerTag },
        File = schedulerProjectDir + File("Dockerfile")
    };
    DockerBuild(buildSettings, "." );
});

Task("ECR Login")
    .Does(()=>{
        StartPowershellScript("Invoke-Expression -Command (aws ecr get-login --no-include-email --region eu-west-1)",
            new PowershellSettings()
                .SetFormatOutput()
                .SetLogOutput()
        );
    });

Task("Unit Tests")
    .IsDependentOn("Build solution")
    .Does(()=>{
        var testProjects = GetFiles("./tests/**/*.csproj");

         foreach(var testProject in testProjects) {
          DotNetCoreTest(testProject.FullPath);
        }
    });


Task("DotCover")
.IsDependentOn("Build Solution")
  .Does(()=>{
    DotCoverAnalyse(
      tool => {
        var settings = new DotNetCoreTestSettings() { NoBuild = true };
        var testProjects = GetFiles("./tests/**/*.csproj");

        foreach(var testProject in testProjects) {
          tool.DotNetCoreTest(testProject.FullPath, settings);
        }
      },
      new FilePath("./test-results/result.html"),
      new DotCoverAnalyseSettings(){
        ReportType = DotCoverReportType.HTML
      }.WithFilter("+:JobAlerts.*").WithFilter("-:*.UI")
      .WithFilter("-:*.Tests")
    );
  });

Task("Publish Docker")
    .IsDependentOn("Build scheduler docker")
    .IsDependentOn("ECR Login")
    .Does(() => {
        DockerPush(dockerTag);
    });

Task("SonarBegin")
  .Does(() => {
     SonarBegin(new SonarBeginSettings{
        Url = SONARQUBE_URL,
        Login = "admin",
        Password = "admin",
        Key = sonarProjectKey,
        Verbose = true,
        DotCoverReportsPath  = "./test-results/result.html",
        Exclusions = "**/*.js"
     });
  });


Task("SonarEnd")
  .Does(() => {
     SonarEnd(new SonarEndSettings{
        Login = "admin",
        Password = "admin"
     });
  });

  Task("Sonar")
  .IsDependentOn("SonarBegin")
  .IsDependentOn("Build solution")
  .IsDependentOn("DotCover")
  .IsDependentOn("SonarEnd");

RunTarget(target);
```

**Comment by devlead** [comment] 2018-09-13 20:58
@ryudice this is not a feature of Cake, by design in the .NET CLI to increase perf it remains resident a while after being executed.

You can tell the .NET CLI to exit i your teardown task by executing
```cake
StartProcess("dotnet", "build-server shutdown");
```

**Comment by devlead** [comment] 2018-09-13 21:07
You can also control using MSBuild properties/arguments
```
Use -p:UseRazorBuildServer=false to disable the Razor (rzc) server.
Use -p:UseSharedCompilation=false to disable the Roslyn (vbcscompiler) server.
For MSBuild, pass /nodeReuse:false on the command line to disable node re-use.
```
or envvars

|key|name|
|----|------|
|MSBUILDDISABLENODEREUSE|false|
|UseRazorBuildServer|false|
|UseSharedCompilation|false|

**Comment by devlead** [comment] 2018-09-28 06:17
Next version of Cake will have an alias for this ( #2287 ).

I'm going to close this now, please re-open or raise an new issue if you're still having issues.

**Closed by devlead** 2018-09-28 06:17 UTC
