### ISSUE TITLE
Enumerate errors so we don't get "Error: One or more errors occurred."

### ISSUE THREAD

**Issue by colinangusmackay** [cake-build/cake#1851] opened 2017-10-01 17:11 UTC
### What You Are Seeing?

When an exception occurs I get the message: `Error: One or more errors occurred.`

### What is Expected?

A more detailed exception message or messages. I realise setting the verbosity to "diagnostic" gives me all this and more, but a little more detail than "One or more errors occurred." would be much better (even if it doesn't include the full stack trace, the underlying exception message(s) would be good).

### What version of Cake are you using?

v0.22.2

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

This error occurs both at a poweshell prompt and on a CI server (Team City)

### How Did You Get This To Happen? (Steps to Reproduce)

A simple way to do this (but most anything that causes an error really) is to run the build specifying a build target that does not exist. e.g.

```
Task("build")
    .Does(()=>
{
  Information("All done!");
});

var target = Argument("target", "build");
Information("Running "+target);
RunTarget(target);
```

Now run this with bootstrap PowerShell script from the example (which explicitly sets the target to "Default") and the output is:

```
PS C:\dev\myapp> .\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Compiling build script...
Running Default
Error: One or more errors occurred.
```

### Output Log
Not relevant. The issue is what is output when the diagnostic switch is turned off.

**Comment by devlead** [comment] 2017-10-01 17:15
Hi, thanks for reporting @colinangusmackay.

This is a duplicate of #1815 , fixed by #1824 which will be shipped when the next release of Cake.

**Closed by devlead** 2017-10-01 17:15 UTC

**Comment by devlead** [comment] 2017-10-01 17:17
Meanwhile running with diagnostic verbosity will output the complete stack trace.

**Comment by colinangusmackay** [comment] 2017-10-01 17:18
Thanks.
