### ISSUE TITLE
Empty folders are not included in a ZIP archive

### ISSUE THREAD

**Issue by vladimir-kazakov** [cake-build/cake#1283] opened 2016-10-13 18:25 UTC
### What You Are Seeing?
I'm trying to create a ZIP archive with pre-defined folder structure. Some folders are empty. After using `Zip("./Package", "Package.zip");`, I see that Package.zip is created, but when I look inside it, there are no empty folders. Only folders with files are included.

### What is Expected?
I expect empty folders to be present in the ZIP archive.

### What version of Cake are you using?
0.16.2.

### Are you running on a 32 or 64 bit system?
64-bit.

### What environment are you running on?  Windows? Linux? Mac?
* Windows 10 (1511).
* Ubuntu 16.04.1.

### Are you running on a CI Server?  If so, which one?
No.

### How Did You Get This To Happen? (Steps to Reproduce)
Create the following folder structure:
```
+ Package
|  + Empty
|  + NotEmpty
|  |  - File.txt
```
In the `build.cake` perform `Zip("./Package", "Package.zip");`.

### Output Log
~~~sh
Feeds used:
  /home/havok/.local/share/NuGet/Cache
  /home/havok/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /home/havok/Projects/Cake/ZipEmptyFolders/tools/packages.config are already installed.
Module directory does not exist.
Analyzing build script...
Analyzing /home/havok/Projects/Cake/ZipEmptyFolders/build.cake...
Processing build script...
Creating script session...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to Cake.exe...
Adding reference to System.Xml.dll...
Adding reference to System.Xml.Linq.dll...
Adding reference to System.Data.dll...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DNU...
Importing namespace Cake.Common.Tools.DNU.Build...
Importing namespace Cake.Common.Tools.DNU.Pack...
Importing namespace Cake.Common.Tools.DNU.Restore...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...

========================================
Default
========================================
Executing task: Default
Creating zip file: /home/havok/Projects/Cake/ZipEmptyFolders/EmptyFolders.zip
Compressing file /home/havok/Projects/Cake/ZipEmptyFolders/Package/NotEmpty/File.txt
Zip successfully created: /home/havok/Projects/Cake/ZipEmptyFolders/EmptyFolders.zip
Finished executing task: Default

Task                          Duration            
--------------------------------------------------
Default                       00:00:00.0924718    
--------------------------------------------------
Total:                        00:00:00.0924718   
~~~

**Comment by gep13** [comment] 2016-10-13 18:27
@vladimir-kazakov is this not the standard outcome? What happens if you do the same operation through compression options in Windows?

**Comment by vladimir-kazakov** [comment] 2016-10-13 18:30
* Build-in archiver on Windows: empty folders are included.
* 7-Zip on Windows: empty folders are included.
* Built-in archiver on Ubuntu: empty folders are included.

**Comment by devlead** [comment] 2016-10-13 18:34
Unfortunately this is by design in the ZipFile class included in the .NET framework, it omits empty directories.

**Comment by gep13** [comment] 2016-10-13 18:40
@vladimir-kazakov you might want to check out the following:

https://www.nuget.org/packages/Cake.Compression/

**Comment by vladimir-kazakov** [comment] 2016-10-13 18:54
@devlead, I've just tried the ZipFile class from the .NET Framework, and it created an archive with empty folders.

I was using the following code:
```
ZipFile.CreateFromDirectory("Package", "Package.zip");
```

**Comment by devlead** [comment] 2016-10-13 19:20
Cool, because MSDN says empty folder will generate an empty archive. Could be we're using another overload or version of the framework (4.5)

**Comment by vladimir-kazakov** [comment] 2016-10-14 06:10
@gep13, unfortunately, Cake.Compression behaves the same way - empty folders are not included in a ZIP.

@devlead, I've tested the behavior of the ZipFile on all versions of .NET Framework from 4.5 to 4.6.2, and I see the correct behavior only starting from 4.6.1.

Speaking of anything below 4.6.1, interestingly enough, the behavior of Mono and .NET Framework is different:
* Mono: doesn't include an empty folder.
* .NET Framework: includes an empty folder it as a file.

**Comment by gep13** [comment] 2016-10-14 06:47
@vladimir-kazakov given the inconsistencies, I don't think relying on there being being folders in the zip file is a good idea.  Why are they required?  What is the use case?

**Comment by vladimir-kazakov** [comment] 2016-10-14 07:03
@gep13, I'm creating a package with an app that has a predefined folders structure for logs. I use Nginx web-server, which is configured to log to one of the empty folders. The problem is that if this folder doesn't exist, Nginx fails to start. Having empty folders in the ZIP archive would make everything simpler, so that it would be possible to just extract files and start the web-server. But now, since empty folders cannot be included in the archive, an additional step in the process is needed that will create these folders, which is a bit inconvenient.

**Comment by gep13** [comment] 2016-10-14 07:05
Ah, I see.  Or you could add an empty file to the folder 😄

**Comment by coxp** [comment] 2016-10-19 19:50
We just call out to the 7zip binary to compress as all the other options aren't very good. Something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake" version="0.16.2" />
    <package id="7-Zip.CommandLine" version="9.20.0" />
</packages>
```
```
Task("Zip-Files")
    .IsDependentOn("Build-Environment-Files")
    .Does(() =>
{
    var packageFile = File("project-v" + parameters.Version.SemVersion + ".7z");
    var packagePath = "../" + packageFile;
	
    var exitCodeWithArgument = StartProcess("tools/7-Zip.CommandLine/tools/7za", new ProcessSettings { 
        Arguments = "a " + packagePath + " " + "./* -mx=5",
        WorkingDirectory = parameters.Paths.Directories.Package
    });
});
```

**Comment by gep13** [comment] 2016-10-19 20:07
@coxp that sounds like a good candidate for an addin to wrap that tool :-)

**Comment by devlead** [comment] 2016-10-20 18:01
As the issue is in the .NET framework I'm going to go ahead and close this issue. Big thanks for your input and research on the issue.

**Closed by devlead** 2016-10-20 18:01 UTC
