### ISSUE TITLE
Failed to install adding 'EnvDTE'

### ISSUE THREAD

**Issue by fleed** [cake-build/cake#2614] opened 2019-08-28 11:56 UTC
I'm getting the following error when running a cake script:

```
Installing addins...
Found package 'EnvDTE 8.0.2' in 'G:/git/resource-service/tools/Addins'.                                         
Package EnvDTE.8.0.2 has already been installed.                                                                        
Successfully installed 'EnvDTE 8.0.2' to G:/git/resource-service/tools/Addins                                   
Executing nuget actions took 2.7 ms                                                                                     
Error: Cake.Core.CakeException: Failed to install addin 'EnvDTE'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\p
rojects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 114
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\project
s\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line
 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
```

*This is the output using the `Diagnostic` verbosity*

I have the following adding and tools:

```
#addin "nuget:?package=Cake.Docker&version=0.10.0"
#tool "nuget:?package=GitVersion.CommandLine&version=4.0.0"

#tool "nuget:?package=Mono.TextTransform&version=1.0.0"
#addin nuget:?package=EnvDTE&version=8.0.2
```

I'm using `Cake` **0.34.1**

**Comment by devlead** [comment] 2019-09-04 07:16
I'm not able to reproduce the issue, first I thought it was a dependency issue but it still installed for me.

Script I tried:
```cake
#addin "nuget:?package=Cake.Docker&version=0.10.0"
#tool "nuget:?package=GitVersion.CommandLine&version=4.0.0"

#tool "nuget:?package=Mono.TextTransform&version=1.0.0"
#addin "nuget:?package=stdole&version=7.0.3303"
#addin "nuget:?package=EnvDTE&version=8.0.2"


 Information(typeof(EnvDTE.DTE));
```

Log using Diagnostic output:
https://gist.github.com/devlead/c25732c75fdb97c5d2bbf8075ebdfe09

That said what are you trying to do with EnvDTE in your Cake script? Might be wrong but my understanding is that it's only supposed to be used within Visual Studio for automating it.

Does what your trying to achieve work in i.e. an simple console application? If so could you create a minimal gist and we can see if we can assist why it works in console application but not in cake.

**Comment by fleed** [comment] 2019-09-06 05:20
@devlead actually I need to download the binaries before running a T4 transformation task. I need to reference a dll from a template, and Cake looked the easiest way to locally deploy the package.
I will test it again and let you know.

**Comment by augustoproiete** [comment] 2021-03-04 21:35
(Moving to GitHub Discussions Q&A)

**Closed** 2021-03-04 21:36 UTC
Labels: Question
