### ISSUE TITLE
bootstrap stalls  whilst 'downloading and installing Rosyln'

### ISSUE THREAD

**Issue by MrTortoise2** [cake-build/cake#888] opened 2016-05-16 13:03 UTC
Was asked to post this as an issue after failing to get it working.

I first met this problem during the getting started tutorial and can reproduce using the example repo. When i run build against the actual cake repo everything works as intended however. 

The shortest repro steps for me are the following
http://cakebuild.net/docs/tutorials/setting-up-a-new-project

the ps to get the bootstrapper seems to work fine, running the build.ps1 is where the problem starts
https://gist.github.com/MrTortoise2/5c2296f5d9eea6f65a97cc6dc980455c

I get the same output from using a single - in the verbosity argument. We spent some time the other night deleting nuget packages and restoring them.

**Comment by devlead** [comment] 2016-05-16 13:16
PowerShell key & values are separated by space and only one dash in keys, so
`.\build.ps1 --verbosity=diagnostic`
should be
`.\build.ps1 -Verbosity Diagnostic`

**Comment by MrTortoise2** [comment] 2016-05-16 13:56
ok the output from that is

```
PS M:\programming\cakeTestHelloWorld> .\build.ps1 -Verbosity Diagnostic
Preparing to run build script...
Running build script...
Analyzing build script...
Analyzing M:/programming/cakeTestHelloWorld/build.cake...
Processing build script...
Creating script session...
Downloading and installing Roslyn...
```

**Comment by devlead** [comment] 2016-05-16 14:18
Does it hang or just exit after `Downloading and installing Roslyn...` ?

Also that does below command output?
```
.\tools\Cake\Cake.exe -Version
```
Latest Cake version should output `Version 0.11.0+Branch.main.Sha.f67efd089db717c4e67bf0e32a9003cd90f67620`
, it should output something like this in diagnostic mode:
```
Analyzing build script...
Analyzing M:/programming/cakeTestHelloWorld/build.cake...
Processing build script...
Creating script session...
Downloading and installing Roslyn...
Installing packages (using https://packages.nuget.org/api/v2)...
Copying files...
Copying Roslyn.Compilers.CSharp.dll...
Copying Roslyn.Compilers.dll...
Deleting installation directory...
```
then adding references etc.

If i.e. on a local harddrive (i.e. c:\temp) clone our example repo does that work? That's a very minimal example so if it works could be a good candidate to compare against. 

That would be something like:
```
C:\temp> git clone https://github.com/cake-build/example.git
Cloning into 'example'...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (4/4), done.
Receiving obje15 (delta 0), reused 0 (delta 0), pack-reused 111
Receiving objects: 100% (115/115), 21.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (42/42), done.
Checking connectivity... done.
C:\tempt> cd .\example\
C:\temp\example [master ≡]> .\build.ps1
```

**Comment by MrTortoise2** [comment] 2016-05-16 14:33
yeah m is local, i tried on c before and started with the example repo. exactly the same

it just hangs on the getting rosyln part. the build version is as you said above
    Version 0.11.0+Branch.main.Sha.f67efd089db717c4e67bf0e32a9003cd90f67620

I have left it on that step for over an hour. It takes me at most 10 mins to clone and build rosyln (probably a lot less i did it 3 days ago). The actual cake repo works fine - it is the bootstrap and the example repo that fail.

**Comment by gep13** [comment] 2016-05-16 14:35
@MrTortoise2 are you behind any sort of proxy that could be causing problems?

**Comment by devlead** [comment] 2016-05-16 14:38
What happens if you run like this in the example repo?
```
.\build.ps1 -Verbosity Diagnostic -Mono
```

Which version if Windows are you running? And is it 32 or 64 bit?

**Comment by MrTortoise2** [comment] 2016-05-16 15:32
no proxy, windows 8.1 enterprise 64 bit.

doing it with -Mono made it work with no errors.

 As soon as i remove that arg then it halts at the downloading and installing rosyln step again.

**Comment by devlead** [comment] 2016-05-16 15:44
Do you get the same issue running experimental version of Roslyn?
```
.\tools\Cake\Cake.exe -Experimental -Verbosity=Diagnostic
```

**Comment by MrTortoise2** [comment] 2016-05-17 18:44
yeah same issue

**Comment by gep13** [comment] 2016-07-19 10:45
@MrTortoise2 are you still seeing this issue?  I was not able to reproduce it.

**Comment by MrTortoise2** [comment] 2016-07-19 11:27
Sorry no idea I just switched to fake.  Can't promise the time but if I get
chance I will check

**Comment by gep13** [comment] 2016-07-19 11:37
@MrTortoise2 not a problem, thank you very much.  For now, I will close this issue, but feel free to re-open it if you are able to check, and are still seeing an issue.  Thanks!

**Closed by gep13** 2016-07-19 11:37 UTC
