### ISSUE TITLE
ParseAssemblyInfo breaks on slightly complex GlobalAssemblyInfo.cs file

### ISSUE THREAD

**Issue by Tdue21** [cake-build/cake#2348] opened 2018-11-02 14:10 UTC
### What You Are Seeing?
I get this error when running the task:
```
An error occurred when executing task 'Calculate Version'.
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Cake.Common.Solution.Project.Properties.AssemblyInfoParser.Parse(FilePath assemblyInfoPath)
   at Submission#0.ParseAssemblyInfo(FilePath assemblyInfoPath)
   at Submission#0.<<Initialize>>b__0_4(ICakeContext ctx)
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
```

My GlobalAssemblyInfo.cs file looks like this: 
```
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCulture("")]
[assembly: AssemblyCompany("XXXXXX")]
[assembly: AssemblyCopyright("Copyright © 2008-2018 by XXXXXX")]
[assembly: AssemblyTrademark("All rights reserved.")]
[assembly: ComVisible(false)]
[assembly: AssemblyProduct("XXXXXX")]

#if(DEBUG)

[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

#if (DatabaseVersion) 
[assembly: Custom.Namespace.Utils.DatabaseVersion(2040002)]
#endif

[assembly: AssemblyVersion("2.4.0.0")]
[assembly: AssemblyFileVersion("2.4.52731.0")]
[assembly: AssemblyInformationalVersion("XXXXX version 2.4")]
```

### What is Expected?
I really expected the method to ignore pieces it does not understand. E.g. our custom `[assembly: DatabaseVersion()]`. But clearly something breaks the method. 

For completeness this is the code of our custom attribute: 
```
    [AttributeUsage(AttributeTargets.Assembly)]
    public class DatabaseVersionAttribute  : Attribute
    {
        public DatabaseVersionAttribute(int databaseVersion)
        {
            DatabaseVersion = databaseVersion;
        }

        public int DatabaseVersion { get; set; }
    }
```

### What version of Cake are you using?
0.30.

### Are you running on a 32 or 64 bit system?
64 bit.

### What environment are you running on?  Windows? Linux? Mac?
Windows 10.

### Are you running on a CI Server?  If so, which one?
Not yet, still early development so it is not on the CI server yet. 

### How Did You Get This To Happen? (Steps to Reproduce)
My task looks like this: 

```
Task("Calculate Version")
    .Does(ctx =>
{
    TeamCity.WriteStatus("Calculating version information.");

    if(!HasEnvironmentVariable("BUILD_VCS_NUMBER"))
    {
        var info = GetSvnDirectoryInfo(parameters.SourcePath).FirstOrDefault();
        var revision = (info != null) ? (int)info.Revision : 0;
        System.Environment.SetEnvironmentVariable("BUILD_VCS_NUMBER", revision.ToString());
    }

    var revisionNo = int.TryParse(EnvironmentVariable("BUILD_VCS_NUMBER"), out var result) ? result : 0;
    var fileVersion = $"{parameters.ProductVersion}.{revisionNo}.{parameters.PatchNumber}";
    var assmVersion = $"{parameters.ProductVersion}.0.0";

    TeamCity.WriteStatus("Updating GlobalAssemblyInfo");

    var assemblyInfoFile = sourcePath.CombineWithFilePath(new FilePath("Common/GlobalAssemblyInfo.cs")).MakeAbsolute(ctx.Environment);

    var infoFile = ParseAssemblyInfo(assemblyInfoFile);

    TeamCity.WriteStatus("Setting TeamCity build number.");
    TeamCity.SetBuildNumber($"{{build.number}} {fileVersion}");

    Information($"Assembly Version: {assmVersion} - File Version: {fileVersion} - Revision {EnvironmentVariable("BUILD_VCS_NUMBER")}.");
})
.OnError(ex => Error(ex.ToString()));

```

### Output Log

[GIST LINK](https://gist.github.com/Tdue21/90cb5f27e067a13fb407dd3ccd3bbb59)

**Comment by patriksvensson** [comment] 2018-11-02 14:30
@Tdue21 Alas, the assembly info parser is really, really stupid (by design) and does not understand custom attributes nor pre-processor directives such as `#if`, `#else` or `#endif`.

**Comment by patriksvensson** [comment] 2018-11-02 14:30
@Tdue21 A solution would be to put these in a separate file which is not parsed.

**Comment by Tdue21** [comment] 2018-11-02 16:13
@patriksvensson  Well, that requires adding another file to hundreds of projects. Not really a good solution 😄 
I get why it might be intentionally stupid, but that also means, that it will is close to useless for many LOB applications. 
Anyway, I ported an earlier powershell solution to the same problem, so I am not going to use the Assembly Info methods at all.

**Comment by patriksvensson** [comment] 2018-11-02 16:45
@Tdue21 Great. I'm going to close this issue. Feel free to reopen it if you want to.

**Closed by patriksvensson** 2018-11-02 16:45 UTC

**Comment by Tdue21** [comment] 2018-11-04 15:36
@Insire True. But it is as much the preprocessor directives that broke it 😄
