### ISSUE TITLE
Tools resolution doesn't respect added 'prerelease' filter

### ISSUE THREAD

**Issue by matkoch** [cake-build/cake#1521] opened 2017-03-06 16:44 UTC
### What You Are Seeing?

Tool "GitVersion" was not updated to v4.0.0-betaxxxx.

### What is Expected?

An update.

### What version of Cake are you using?

Latest I guess on Win10/x64.

### How Did You Get This To Happen? (Steps to Reproduce)

- Had `#tool "nuget:?package=GitVersion.CommandLine"`
- Changed to `#tool "nuget:?package=GitVersion.CommandLine&prerelease"`
- Nupkg inside `tools` folder was still the stable release

This hurts probably the most with build servers.

**Comment by patriksvensson** [comment] 2017-03-06 20:12
@matkoch You will need to clear the folder manually before the new version will be downloaded.

**Comment by matkoch** [comment] 2017-03-06 20:28
@patriksvensson Shouldn't the `#tool` directive always pick the highest possible package, if no version was specified? I think that makes sense.

**Comment by patriksvensson** [comment] 2017-03-12 12:14
@matkoch Not strange. You might notice that the tools folders are not versioned. We simply assume that the versions are correct. There is an issue for fixing all this, but nothing that is being actively worked on.

**Comment by boebeng** [comment] 2017-07-11 14:05
@patriksvensson Is there any progress on this? I recently started with Cake build and it seems quite interesting and we would like to replace psake with Cake build. This issue is somehow blocking me.
Is there a workaround? For example an automatism to delete the tools folder upfront?

**Comment by gep13** [comment] 2017-08-04 12:47
Closing as a duplicate of https://github.com/cake-build/cake/issues/753

**Closed by gep13** 2017-08-04 12:47 UTC

**Comment by daveaglick** [comment] 2017-08-04 13:42
For anyone interested in this issue, there's an easy workaround. I just stick this in my PowerShell bootstraper:

```
# Delete the tools and addins folders
Remove-Item $TOOLS_DIR\* -Force -Recurse -ErrorAction Ignore
```

You can make it more specific too if you know it's only one tool or addin you want to ensure is always fresh.

**Comment by matkoch** [comment] 2017-08-04 13:44
@daveaglick thanks, `-ErrorAction Stop` would be better I think. Otherwise you could have strange side effects again.
