### ISSUE TITLE
Globbing is missing some documentation.

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake#4043] opened 2022-11-02 11:07 UTC
Currently, the only documentation seems to be https://cakebuild.net/blog/2018/12/cake-v0.31.0-released#globber-improvements

The Documentation should get its own section, containing examples and descriptions of what does, and what does not, work.

Also, the API (probably at https://cakebuild.net/api/Cake.Core.IO/GlobPattern/) should contain at least some hints and/or a reference to the above described section.

**Comment by pascalberger** [comment] 2022-11-07 20:58
Seems to be a duplicate of https://github.com/cake-build/website/issues/1224

**Closed by pascalberger** 2022-11-07 20:58 UTC
Labels: Documentation
