### ISSUE TITLE
Error: TrustFailure

### ISSUE THREAD

**Issue by maxpa1n87** [cake-build/cake#676] opened 2016-02-05 23:16 UTC
Hi, I'am trying to build from git. Getting:
WARNING: Error: TrustFailure
Unable to find version '0.8.0' of package 'Cake'.
Could not restore NuGet packages.
Running ./build.sh --prefix=/usr
OS is Debian/Jessie 64bit.

**Comment by patriksvensson** [comment] 2016-02-05 23:25
@maxpa1n87 I think this has to do with that you dont have any trusted root certificates in mono's certificate store.

You can read more about it here in the NuGet documentaiton: https://docs.nuget.org/contribute/setting-up-the-nuget-development-environment

**Comment by maxpa1n87** [comment] 2016-02-05 23:29
Thank you. I think I need to install nuget first.

**Comment by patriksvensson** [comment] 2016-02-05 23:31
@maxpa1n87 NuGet is downloaded as part of the `build.sh` bootstrapper script so you shouldn't have to install anything except perhaps the certificates (and Mono) to build Cake.

**Comment by maxpa1n87** [comment] 2016-02-05 23:34
I see. Now I get the following error building cake Unit/AssemblyFrameworkNameParserTests.cs(14,14): error CS0012: The type `System.Attribute' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by maxpa1n87** [comment] 2016-02-05 23:35
I have compiled mono from git.

**Comment by patriksvensson** [comment] 2016-02-05 23:59
@maxpa1n87 Sounds like an issue with the Mono version you got installed and I have honestly no idea how to fix it since I can't reproduce it on my Windows or OS X system (which runs Mono 4.2.1).

Maybe @Redth knows something about this. Otherwise I think your best bet on resolving this is asking on a Mono forum or Stackoverflow.

Sorry that I can't be of more help.

**Comment by maxpa1n87** [comment] 2016-02-06 20:56
Hi @patriksvensson, fixed some issues installing https://github.com/directhex/xamarin-referenceassemblies-pcl. I sill get this error:
`Unit/AssemblyFrameworkNameParserTests.cs(14,14): error CS0012: 'The type System.Attribute' is defined in an assembly that is not referenced. Consider adding a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`
I'am using Mono JIT compiler version 4.3.3 (master/636c0c9 Sa 6. Feb 18:28:25 CET 2016) with PCL Reference Assemblies installed from github. Is the cake targeting .NET version 4.0? But is referencing 4.5 Assemblies?

**Comment by patriksvensson** [comment] 2016-02-06 20:58
Cake is targeting .Net framework 4.5.

**Comment by maxpa1n87** [comment] 2016-02-06 21:15
Ok. I looked up System.Runtime.dll, but there is no such file. Only System.Runtime.X where X can be Serialization, Remoting etc. Why should I reference System.Runtime?

**Comment by maxpa1n87** [comment] 2016-02-07 10:22
Hi, I tried mono 4.2.2.30 and now cake does build.

**Comment by patriksvensson** [comment] 2016-02-07 10:24
Perfect. Glad you got it working.

**Closed** 2016-02-07 10:24 UTC
