### ISSUE TITLE
NuGetPushSettings.Source: incorrect documentation

### ISSUE THREAD

**Issue by Jericho** [cake-build/cake#1213] opened 2016-09-06 20:21 UTC
Regarding NuGetPushSettings.Source: documentation says `If not specified, nuget.org is used`. However, when this value is null I am getting the following error: `Source parameter was not specified`.

The documentation in question is here: http://cakebuild.net/api/cake.common.tools.nuget.push/bcd6313b
and also here: http://cakebuild.net/api/cake.common.tools.nuget.push/bcd6313b/83747a07

By the way, since there is no 'default' value, we should document the most common values (e.g.: nuget.org, myget, etc.).

**Comment by devlead** [comment] 2016-09-06 20:45
This is a change on the NuGet.exe, we've added a note on the aliases
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L295-L296

So it's mandatory depending which version of the tool you're using, could likely make even more clear if we added it here  too
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Push/NuGetPushSettings.cs#L23

**Comment by Jericho** [comment] 2016-09-06 20:47
I understand that it's mandatory, but the documentation says otherwise.

**Comment by Jericho** [comment] 2016-09-06 20:52
Also, despite my best efforts I could not find the appropriate value for nuget. I asked about it on gitter and @gep13 told me it was https://nuget.org/api/v2/package.

I'm sure I'm not the only one who struggle to figue this out so that's why I suggested documenting the URL for nuget, myget, etc.

**Comment by devlead** [comment] 2016-09-06 21:16
Yes, agree, great feedback.

We've documented this change of behavior on the aliases i.e.
http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572/41c53943

But not updated docs on settings source property, which would be a great addition to clarify too.
Adding the nuget.org push url as an example also sounds like an good addition to [here](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Push/NuGetPushSettings.cs#L23)

Our docs are auto generated from source code, there's one source of truth. Gladly accept good docs PRs, once merged, they'll show up on our web post next release.

You can read more about the NuGet authoring in general  [here](https://docs.nuget.org/Create/Creating-and-Publishing-a-Package)

The docs were correct when written, we just have to get with the times ;) Parameter it's still optional with any nuget.exe version pre 3.4.2 or if  you have a default push source specified in your nuget.config.
```xml
<add key="DefaultPushSource" value="http://MyRepo/ES/api/v2/package" />
```
You can read more about nuget.config [here](https://docs.nuget.org/consume/nuget-config-file)

**Comment by gep13** [comment] 2018-02-14 17:40
@Jericho i don't think this work has been completed yet. Why close the issue?

**Comment by Jericho** [comment] 2018-02-14 17:42
@gep13 a year and a half later, I didn't think anybody was paying attention anymore.

**Comment by gep13** [comment] 2018-02-14 17:47
In Open Source terms, that really isn't long. I think the first PR I created took 2 years to be pulled in. If the issue is still present, I would prefer that it stay open.

**Closed** 2018-03-13 17:35 UTC
Labels: Documentation
