### ISSUE TITLE
Load preprocessor directive inconsistent with Addin

### ISSUE THREAD

**Issue by richardgavel** [cake-build/cake#2115] opened 2018-04-05 16:55 UTC
### What You Are Seeing?

When using load pre-processor directive and nuget scheme, "&prerelease" does not pull a pre-release nuget package, as described in the docs for addin directive with nuget scheme (https://cakebuild.net/docs/fundamentals/preprocessor-directives)

### What is Expected?

#load "nuget:?package=utilities.cake&prelease" would pull the latest package, including prelease ones.

### What version of Cake are you using?

0.25.0

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Additional notes

In researching the code, I did figure out I could use &prerelease=true as a workaround. But this conflicts with the documentation.

**Comment by patriksvensson** [comment] 2018-04-06 06:04
@richardgavel That should work afaik.

I noticed that you spelled `prerelease` wrong in your load directive. Can you try changing it to `#load "nuget:?package=utilities.cake&prerelease"` and see if it works as expected.

**Comment by augustoproiete** [comment] 2021-01-16 03:22
This has been fixed via https://github.com/cake-build/cake/issues/2595 and will be available in Cake v1.0.0 RTM.

You can test it today with the release candidate [Cake v1.0.0-rc0002](https://cakebuild.net/blog/2020/12/cake-v1.0.0-rc0002-released).

---

Closing as Duplicate of https://github.com/cake-build/cake/issues/2595

**Closed by augustoproiete** 2021-01-16 03:22 UTC
Labels: Duplicate
