### ISSUE TITLE
Problem FileCopy to UNC path

### ISSUE THREAD

**Issue by lvmgeo** [cake-build/cake#2409] opened 2018-12-21 09:50 UTC
### What You Are Seeing?
There is a problem with file copy to UNC path

```            Information("Instalation publishing start...");
            Information($"Does folder exists {DirectoryExists(workPath)} ...");
            Information($"Folder Path {workPath} ...");
            Information($"Does file exists {FileExists(InstallFile)} ...");
            Information($"File Path {InstallFile} ...");
            CopyFileToDirectory(InstallFile, workPath);
```

Ouput is:
```
Instalation publishing start...
Does folder exists True ...
Folder Path //install/install/XXX/Release ...
Does file exists True ...
File Path ../XXX/Setup_3.15.38.0.msi ...
An error occurred when executing task 'Publish'.
Error: One or more errors occurred.
        The directory '/install/install/XXX/Release' does not exist.
```
### What is Expected?
File Copyed to UNC location

### What version of Cake are you using?
0.31.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Microsoft Windows [Version 10.0.17134.471] 64bit

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
see code in What You Are Seeing? section

### Output Log
see code in What You Are Seeing? section

**Comment by augustoproiete** [comment] 2021-02-02 04:55
Hi @lvmgeo It's been a long time, but just following up on this issue.

Tried to repro just now o both Cake 0.31.0 and Cake 1.0.0-rc0003 (latest as of this writing) and in both cases copying the files works as expected.

- build.cake

```csharp
var sourceFilePath = MakeAbsolute(FilePath.FromString("./repro--cake-build-2409.cake"));
var destDirectoryPath = MakeAbsolute(DirectoryPath.FromString(@"\\myfileshare\augusto\temp"));

CreateDirectory(destDirectoryPath);

Information($"Does folder exists {DirectoryExists(destDirectoryPath)} ...");
Information($"Folder Path {destDirectoryPath} ...");
Information($"Does file exists {FileExists(sourceFilePath)} ...");
Information($"File Path {sourceFilePath} ...");
CopyFileToDirectory(sourceFilePath, destDirectoryPath);
```

#### Cake 0.31.0

```powershell
Compiling build script...
Creating directory \\myfileshare\augusto\temp
Does folder exists True ...
Folder Path \\myfileshare\augusto\temp ...
Does file exists True ...
File Path C:/augustoproiete/cake-tool-0-31-0/repro--cake-build-2409.cake ...
Copying file repro--cake-build-2409.cake to \\myfileshare\augusto\temp\repro--cake-build-2409.cake
```

#### Cake 1.0.0-rc0003

```powershell
Compiling build script...
Creating directory \\myfileshare\augusto\temp
Does folder exists True ...
Folder Path \\myfileshare\augusto\temp ...
Does file exists True ...
File Path C:/augustoproiete/cake-tool-1-0-0--rc0003/repro--cake-build-2409.cake ...
Copying file repro--cake-build-2409.cake to \\myfileshare\augusto\temp\repro--cake-build-2409.cake
```

---

In both versions I confirmed the file is successfully copied to the destination folder in the file share.

Closing as cannot reproduce. Feel free to reopen if you or anyone can provide a repro example.

**Closed** 2021-02-02 04:55 UTC
Labels: Invalid
