### ISSUE TITLE
Remove delegating tasks from report

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#123] opened 2014-11-27 11:04 UTC
When running delegating tasks (tasks that *only* explicitly point out dependencies but has no action), those tasks should be excluded from the report.

The following script:

```csharp
Task("A").Does(() => {});
Task("B").IsDependentOn("A").Does(() => {});
Task("C").IsDependentOn("A").Does(() => {});

Task("D")
  .IsDependentOn("B")
  .IsDependentOn("C");
```

Should result in the following:

```
Task                          Duration
--------------------------------------------------
A                             00:00:00.0032991
B                             00:00:00.2870660
C                             00:00:00.0000407
--------------------------------------------------
Total:                        00:00:00.2904058
```

Where the task `D` is excluded.

**Comment by gep13** [comment] 2016-04-19 09:37
Closed as duplicate of #639

**Closed by gep13** 2016-04-19 09:37 UTC
Labels: Improvement
