### ISSUE TITLE
Reference NuGet dependencies installed via the #addin directive

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#787] opened 2016-03-25 10:24 UTC
When installing a nuget package via the `#addin` directive, the package's dependencies should also be referenced.

**Comment by daveaglick** [comment] 2016-04-20 17:25
Is the intent to recursively descend the dependency tree, or just reference the direct dependencies of the addin?

**Comment by devlead** [comment] 2016-04-20 17:28
Well intent would be to reference anything needed by the addin, so likely yes. Basically equivalent of a nuget install.

**Comment by daveaglick** [comment] 2016-04-20 17:32
I'll be watching the progress on this one with interest as I haven't quite figured out the best way to do this myself.

In Wyam I let NuGet fulfil all of it's requested packages, including transitive dependencies, and then just walk the entire packages collection and add references for every assembly I find. I haven't upgraded to the v3 libraries yet, which I understand are very different, so I'm sure all my code will break when I do.

**Comment by devlead** [comment] 2016-04-20 17:37
@daveaglick V3 is different, nuget core is depreciated and replaced by a number of undocumented assemblies.

There's any issue due it though NuGet/Home#2243

**Comment by daveaglick** [comment] 2016-04-20 17:39
Yeah, I've been stalling and putting it off. "Undocumented assemblies" doesn't sound like my idea of a fun evening of hacking.

**Comment by devlead** [comment] 2016-04-20 17:44
NuGet V3 despite of being "RTM" doesn't feel fully baked.
It's a bit too much code to effortless browse without docs, sample or even a spec at hand.
Just a blog post with a simple minimal install package sample would be a good quick start to grasp what's needed.

**Comment by devlead** [comment] 2017-09-24 10:01
@mholo65 this is avail opt in now right?

**Comment by mholo65** [comment] 2017-09-24 10:24
@devlead yeah, but it doesn take target framework into account. I've another issue for that here https://github.com/cake-build/cake/issues/1801

**Comment by devlead** [comment] 2017-09-26 08:51
@mholo65 so is this a matter of documentation or does something need to be done to close this issue?

**Closed** 2017-09-30 14:46 UTC
Labels: Improvement

**Comment by nlowe** [comment] 2017-10-18 16:55
So if I'm understanding #1848 correctly, we need to use the in-process nuget client if we want support for installing addon dependencies?

**Comment by devlead** [comment] 2017-10-18 16:56
@nlowe Correct.

**Comment by nlowe** [comment] 2017-10-18 17:28
@devlead I enabled the in-process nuget client and added `&loaddependencies=true` to the addin I'm trying to load. A folder is created for the dependencies and they are downloaded, but it seems they're not referenced. When I turn on assembly binding logging, I see that the addin folder isn't even searched:

```
=== Pre-bind state information ===
LOG: DisplayName = My.Dependency, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942
 (Fully-specified)
LOG: Appbase = file:///C:/Users/nlowe/Projects/MyProject/tools/Cake/
LOG: Initial PrivatePath = NULL
Calling assembly : Cake.MyAddin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\nlowe\Projects\MyProject\tools\Cake\Cake.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: My.Dependency, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Cake/My.Dependency.DLL.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Cake/My.Dependency/My.Dependency.DLL.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Cake/My.Dependency.EXE.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Cake/My.Dependency/My.Dependency.EXE.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Addins/Cake.MyAddin.1.1.0/lib/net46/My.Dependency.DLL.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Addins/Cake.MyAddin.1.1.0/lib/net46/My.Dependency/My.Dependency.DLL.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Addins/Cake.MyAddin.1.1.0/lib/net46/My.Dependency.EXE.
LOG: Attempting download of new URL file:///C:/Users/nlowe/Projects/MyProject/tools/Addins/Cake.MyAddin.1.1.0/lib/net46/My.Dependency/My.Dependency.EXE.
```

If this is not the expected behavior I can open a new issue.

**Comment by mholo65** [comment] 2017-10-18 17:43
@nlowe, no this is not expected behaviour. Could you raise an issue including minimal steps to reproduce?

**Comment by jnm2** [comment] 2017-11-04 17:22
I'm trying to create an addin where you don't have to do anything special to an OOB cake script. Rather than bundling dependencies inside the nupkg, I'd much rather use nuspec dependencies. I see the `netstandard1.6` dependencies are installed in the correct addins folder but they are not referenced when running Cake under CoreCLR, causing the addin to fail to load. Am I doing something wrong, or can this state of affairs be addressed?

**Comment by devlead** [comment] 2017-11-04 17:30
@jnm2 Have you opted for using in proc and load dependencies?

As per documented at:
https://cakebuild.net/docs/fundamentals/default-configuration-values

**Comment by jnm2** [comment] 2017-11-04 18:15
The problem is that this is an addin. It should work out of the box and without constraining folks' build script setups.

**Comment by devlead** [comment] 2017-11-04 18:38
If opt in sort it now, then it'll work out of the box when we make it default in the future.

**Comment by jnm2** [comment] 2017-11-04 20:35
As soon as I add `--nuget_useinprocessclient=true`, it stops respecting the nuget.config. I added `--nuget_source=` but then it didn't download anything from nuget.org. So I can't even test that.

**Comment by jnm2** [comment] 2017-11-04 21:17
Oh no, I just hit a dead end on the other side! It doesn't look like it's possible to include System.Data.SqlClient in the nupkg– it doesn't get copied to build output but rather listed in a .deps.json which I guess I'd have to parse and resolve? Plus it's not really the right solution since another addin may load a conflicting version of the System.Data.SqlClient package.

Looks like the only way for this addin to succeed on .NET Core is for Cake to automatically reference its dependencies without requiring the `--nuget_useinprocessclient=true` parameter.
